(ns whatanime.components.grommet
  (:refer-clojure :exclude [Box List])
  (:require-macros [whatanime.components.grommet :refer [def-components]])
  (:require [reagent.core :refer [adapt-react-class]]
            [cljsjs.grommet]))

(def-components
  ;; Layout
  Box
  Columns
  Layer
  Split

  ;; Structure
  App
  Article
  Card
  Footer
  Header
  Hero
  Notification
  Section
  Sidebar
  Toast
  Value

  ;; Text
  Heading
  Headline
  Label
  Markdown
  Paragraph
  Quote
  Timestamp
  Title

  ;; Controls
  Accordion
  Anchor
  Button
  Menu
  Search
  Tabs
  Tip

  ;; Forms
  CheckBox
  DateTime
  Form
  FormField
  LoginForm
  NumberInput
  RadioButton
  SearchInput
  Select
  TextInput

  ;; Listing
  List
  Table
  TableHeader
  Tiles
  Tile

  ;; Visualization
  ChartArea
  ChartAxis
  ChartBar
  ChartBase
  ChartGrid
  ChartHotSpots
  ChartLayers
  ChartLine
  ChartMarker
  ChartMarkerLabel
  ChartRange
  Distribution
  Legend
  Map
  Meter
  SunBurst
  Topology
  WorldMap

  ;; Icons (Set)
  ThreeDIcon 
  AccessAccessibilityIcon 
  AccessAdIcon 
  AccessAssistListeningIcon 
  AccessBrailleIcon 
  AccessSignIcon 
  AccessTtyIcon 
  AccessVolumeControlIcon 
  AccessWheelchairActiveIcon 
  AccessWheelchairIcon 
  AccessibleIcon 
  AchievementIcon 
  ActionIcon 
  ActionsIcon 
  AddChapterIcon 
  AddCircleIcon 
  AddIcon 
  AedIcon 
  AggregateIcon 
  AidOptionIcon 
  AidIcon 
  AlarmIcon 
  AlertIcon 
  AnalyticsIcon 
  AnnounceIcon 
  AppsIcon 
  ArchiveIcon 
  ArticleIcon 
  AscendIcon 
  AtmIcon 
  AttachmentIcon 
  AttractionIcon 
  BabyIcon 
  BackTenIcon 
  BarChartIcon 
  BarIcon 
  BasketIcon 
  BlogIcon 
  BookIcon 
  BookmarkIcon 
  BottomCornerIcon 
  BrandAppleAppStoreIcon 
  BrandCodepenEditIcon 
  BrandCodepenTryIcon 
  BrandGooglePlayIcon 
  BrandGrommetOutlineIcon 
  BrandGrommetPathIcon 
  BrandHpeElementOutlineIcon 
  BrandHpeElementPathIcon 
  BrandHpeLabsInsigniaOutlineIcon 
  BrandHpeLabsInsigniaIcon 
  BrandHpeStackCenteredIcon 
  BrandHpeStackIcon 
  BriefcaseIcon 
  BrushIcon 
  BugIcon 
  BundleIcon 
  BusIcon 
  BusinessServiceIcon 
  CafeteriaIcon 
  CalculatorIcon 
  CalendarIcon 
  CameraIcon 
  CapacityIcon 
  CarIcon 
  CaretBackIcon 
  CaretDownIcon 
  CaretNextIcon 
  CaretPreviousIcon 
  CaretUpIcon 
  CartIcon 
  CatalogOptionIcon 
  CatalogIcon 
  ChannelIcon 
  ChapterAddIcon 
  ChapterNextIcon 
  ChapterPreviousIcon 
  ChatIcon 
  CheckboxSelectedIcon 
  CheckboxIcon 
  CheckmarkIcon 
  CircleInformationIcon 
  CirclePlayIcon 
  CircleQuestionIcon 
  ClearOptionIcon 
  ClearIcon 
  CliIcon 
  ClipboardIcon 
  ClockIcon 
  CloneIcon 
  CloseIcon 
  ClosedCaptionIcon 
  CloudComputerIcon 
  CloudDownloadIcon 
  CloudSoftwareIcon 
  CloudUploadIcon 
  CloudIcon 
  ClusterIcon 
  CoatCheckIcon 
  CodeIcon 
  ColumnsIcon 
  CompareIcon 
  CompassIcon 
  ComplianceIcon 
  ConfigureIcon 
  ConnectIcon 
  ContactInfoIcon 
  ContactIcon 
  ContractIcon 
  CopyIcon 
  CreditCardIcon 
  CubeIcon 
  CubesIcon 
  CurrencyIcon 
  CursorIcon 
  CutIcon 
  CycleIcon 
  DashboardIcon 
  DatabaseIcon 
  DeliverIcon 
  DeployIcon 
  DescendIcon 
  DesktopIcon 
  DetachIcon 
  DiamondIcon 
  DirectionsIcon 
  DislikeIcon 
  DocumentCloudIcon 
  DocumentConfigIcon 
  DocumentCsvIcon 
  DocumentDownloadIcon 
  DocumentExcelIcon 
  DocumentExeIcon 
  DocumentImageIcon 
  DocumentLockedIcon 
  DocumentMissingIcon 
  DocumentNotesIcon 
  DocumentOutlookIcon 
  DocumentPdfIcon 
  DocumentPerformanceIcon 
  DocumentPptIcon 
  DocumentRtfIcon 
  DocumentSoundIcon 
  DocumentStoreIcon 
  DocumentTestIcon 
  DocumentTextIcon 
  DocumentThreatIcon 
  DocumentTimeIcon 
  DocumentTransferIcon 
  DocumentTxtIcon 
  DocumentUpdateIcon 
  DocumentUploadIcon 
  DocumentUserIcon 
  DocumentVerifiedIcon 
  DocumentVideoIcon 
  DocumentWindowsIcon 
  DocumentWordIcon 
  DocumentZipIcon 
  DocumentIcon 
  DomainIcon 
  DownIcon 
  DownloadIcon 
  DragIcon 
  DriveCageIcon 
  DuplicateIcon 
  EditIcon 
  EjectIcon 
  ElevatorIcon 
  EmergencyIcon 
  EmptyCircleIcon 
  EscalatorIcon 
  ExpandIcon 
  FanIcon 
  FastForwardIcon 
  FavoriteIcon 
  FilterIcon 
  FingerPrintIcon 
  FlagIcon 
  FolderCycleIcon 
  FolderOpenIcon 
  FolderIcon 
  FormAddIcon 
  FormAttachmentIcon 
  FormCalendarIcon 
  FormCheckmarkIcon 
  FormClockIcon 
  FormCloseIcon 
  FormCutIcon 
  FormDownIcon 
  FormEditIcon 
  FormFilterIcon 
  FormFolderIcon 
  FormLocationIcon 
  FormLockIcon 
  FormNextLinkIcon 
  FormNextIcon 
  FormPreviousLinkIcon 
  FormPreviousIcon 
  FormRefreshIcon 
  FormScheduleIcon 
  FormSearchIcon 
  FormSubtractIcon 
  FormTrashIcon 
  FormUpIcon 
  FormUploadIcon 
  ForwardTenIcon 
  GalleryIcon 
  GamepadIcon 
  GiftIcon 
  GlobeIcon 
  GridIcon 
  GroupIcon 
  GrowIcon 
  HaltIcon 
  HelpIcon 
  HistoryIcon 
  HomeIcon 
  HostMaintenanceIcon 
  HostIcon 
  IceCreamIcon 
  ImageIcon 
  ImpactIcon 
  InProgressIcon 
  InboxIcon 
  IndicatorIcon 
  InfoIcon 
  InheritIcon 
  InspectIcon 
  InstallOptionIcon 
  InstallIcon 
  IntegrationIcon 
  IterationIcon 
  JavaIcon 
  LanguageIcon 
  LaunchIcon 
  LayerIcon 
  LicenseIcon 
  LikeIcon 
  LineChartIcon 
  LinkBottomIcon 
  LinkDownIcon 
  LinkNextIcon 
  LinkPreviousIcon 
  LinkTopIcon 
  LinkUpIcon 
  LinkIcon 
  LocalIcon 
  LocationPinIcon 
  LocationIcon 
  LockIcon 
  LoginIcon 
  LogoutIcon 
  LoungeIcon 
  MagicIcon 
  MailOptionIcon 
  MailIcon 
  ManualIcon 
  MapLocationIcon 
  MapIcon 
  MenuIcon 
  MicrophoneIcon 
  MoneyIcon 
  MonitorIcon 
  MoreIcon 
  MultipleIcon 
  MusicIcon 
  NavigateIcon 
  NewWindowIcon 
  NewIcon 
  NextIcon 
  NodesIcon 
  NoteIcon 
  NotesIcon 
  NotificationIcon 
  ObjectGroupIcon 
  ObjectUngroupIcon 
  OptimizeIcon 
  OrganizationIcon 
  OverviewIcon 
  PaintIcon 
  PanIcon 
  PauseFillIcon 
  PauseIcon 
  PersonalComputerIcon 
  PieChartIcon 
  PinIcon 
  PlanIcon 
  PlatformAmazonIcon 
  PlatformAndroidIcon 
  PlatformAppleIcon 
  PlatformArchlinuxIcon 
  PlatformArubaIcon 
  PlatformCentosIcon 
  PlatformChromeIcon 
  PlatformCloudlinuxIcon 
  PlatformDebianIcon 
  PlatformDockerIcon 
  PlatformDosIcon 
  PlatformDropboxIcon 
  PlatformEdgeIcon 
  PlatformFedoraIcon 
  PlatformFirefoxIcon 
  PlatformFreebsdIcon 
  PlatformGoogleIcon 
  PlatformHadoopIcon 
  PlatformHerokuIcon 
  PlatformHortonIcon 
  PlatformHpIcon 
  PlatformHpiIcon 
  PlatformInternetExplorerIcon 
  PlatformJavaIcon 
  PlatformMandrivaIcon 
  PlatformMysqlIcon 
  PlatformNortonIcon 
  PlatformOnedriveIcon 
  PlatformOperaIcon 
  PlatformOracleIcon 
  PlatformPiedPiperIcon 
  PlatformRaspberryIcon 
  PlatformReactjsIcon 
  PlatformRedhatIcon 
  PlatformSafariOptionIcon 
  PlatformSafariIcon 
  PlatformScoIcon 
  PlatformSolarisIcon 
  PlatformSuseIcon 
  PlatformSwiftIcon 
  PlatformTurbolinuxIcon 
  PlatformUbuntuIcon 
  PlatformUnixwareIcon 
  PlatformVmwareIcon 
  PlatformWindowsLegacyIcon 
  PlatformWindowsIcon 
  PlayFillIcon 
  PlayIcon 
  PowerIcon 
  PreviousIcon 
  PrintIcon 
  RadialSelectedIcon 
  RadialIcon 
  RefreshIcon 
  ResourcesIcon 
  RestaurantIcon 
  RestroomMenIcon 
  RestroomWomenIcon 
  RestroomIcon 
  ResumeIcon 
  RevertIcon 
  RewindIcon 
  RiskIcon 
  RobotIcon 
  RssIcon 
  RunIcon 
  SatelliteIcon 
  SaveIcon 
  ScanIcon 
  ScheduleNewIcon 
  SchedulePlayIcon 
  ScheduleIcon 
  SchedulesIcon 
  ScorecardIcon 
  SearchAdvancedIcon 
  SearchIcon 
  SecureIcon 
  SelectIcon 
  SelectionIcon 
  SendIcon 
  ServerClusterIcon 
  ServerIcon 
  ServersIcon 
  ServicePlayIcon 
  ServicesIcon 
  SettignsOptionIcon 
  SettingsOptionIcon 
  ShareIcon 
  ShieldSecurityIcon 
  ShieldIcon 
  ShiftIcon 
  ShopIcon 
  SidebarIcon 
  SocialAmazonIcon 
  SocialAmexIcon 
  SocialBitcoinIcon 
  SocialCodepenIcon 
  SocialCreativeCommonsIcon 
  SocialDropboxIcon 
  SocialFacebookOptionIcon 
  SocialFacebookIcon 
  SocialGithubIcon 
  SocialGooglePlusIcon 
  SocialGoogleWalletIcon 
  SocialInstagramIcon 
  SocialLinkedinOptionIcon 
  SocialLinkedinIcon 
  SocialMailIcon 
  SocialMastercardIcon 
  SocialMediumIcon 
  SocialPaypalIcon 
  SocialPinterestIcon 
  SocialProductHuntIcon 
  SocialRedditIcon 
  SocialSkypeIcon 
  SocialSlackIcon 
  SocialSnapchatIcon 
  SocialSquareIcon 
  SocialStackOverflowIcon 
  SocialStripeIcon 
  SocialTumblrIcon 
  SocialTwitterIcon 
  SocialVimeoIcon 
  SocialVineIcon 
  SocialVisaIcon 
  SocialWordpressIcon 
  SocialYoutubeIcon 
  SortIcon 
  SplitIcon 
  SplitsIcon 
  StakeholderIcon 
  Standards3dEffectsIcon 
  StandardsConnectivityIcon 
  StandardsCss3Icon 
  StandardsDeviceIcon 
  StandardsFireballIcon 
  StandardsHtml5Icon 
  StandardsMultimediaIcon 
  StandardsOfflineStorageIcon 
  StandardsPerformanceIcon 
  StandardsSematicsIcon 
  StarHalfIcon 
  StarIcon 
  StepsOptionIcon 
  StepsIcon 
  StopFillIcon 
  StopIcon 
  StorageIcon 
  StreetViewIcon 
  SubtractCircleIcon 
  SubtractIcon 
  SupportIcon 
  SyncIcon 
  SystemIcon 
  TableAddIcon 
  TableIcon 
  TagIcon 
  TargetIcon 
  TaskIcon 
  TasksIcon 
  TechnologyIcon 
  TemplateIcon 
  TerminalIcon 
  TestDesktopIcon 
  TestIcon 
  TextWrapIcon 
  ThreatsIcon 
  TicketIcon 
  TipIcon 
  ToastIcon 
  ToolsIcon 
  TooltipIcon 
  TopCornerIcon 
  TransactionIcon 
  TrashIcon 
  TreeOptionIcon 
  TreeIcon 
  TriggerIcon 
  TrophyIcon 
  TroubleshootIcon 
  UnlinkIcon 
  UnlockIcon 
  UpIcon 
  UpdateIcon 
  UpgradeIcon 
  UploadIcon 
  UserAddIcon 
  UserAdminIcon 
  UserExpertIcon 
  UserFemaleIcon 
  UserManagerIcon 
  UserNewIcon 
  UserPoliceIcon 
  UserSettingsIcon 
  UserWorkerIcon 
  UserIcon 
  ValidateIcon 
  VideoIcon 
  ViewIcon 
  VirtualMachineIcon 
  VmMaintenanceIcon 
  VolumeLowIcon 
  VolumeMuteIcon 
  VolumeIcon 
  VulnerabilityIcon 
  WaypointIcon 
  WorkshopIcon 
  ZoomInIcon 
  ZoomOutIcon

  ;; Icons (Misc)
  PulseIcon
  SocialShare
  SpinningIcon
  StatusIcon
  SVGIcon

  ;; Media
  Carousel
  Image
  Video

  )

